# step12_postgres/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret  # 이름을 좀 더 직관적인 db-secret으로 변경했습니다.
type: Opaque
stringData:
  POSTGRES_USER: "scott"
  POSTGRES_PASSWORD: "tiger"