# step11.../deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-test-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-test
  template:
    metadata:
      labels:
        app: secret-test
    spec:
      containers:
      - name: db-test-container
        image: alpine # 가벼운 테스트용 리눅스 이미지
        command: ["sleep", "3600"]
        env:
        - name: DB_PASSWORD
          # 위 환경변수 값을
          valueFrom:
            secretKeyRef:
              # 이 이름의 SECRET에
              name: db-pass-secret
              # 이 키값으로 저장되어있는 VALUE를 읽어와서 넣겠다
              key: POSTGRES_PASSWORD